# Generated by Django 6.0.7 on 2026-08-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
