# Generated by Django 6.0.7 on 2026-08-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="qr_image",
            field=models.ImageField(
                upload_to="qr_codes/",
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_number",
            field=models.CharField(
                max_length=30,
                unique=True,
                blank=True,
            ),
        ),
    ]