# Generated by Django 6.0.7 on 2026-08-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_booking_ticket_qr_image_and_more'),
        ('tickets', '0003_ticket_booking'),
    ]

    operations = [
    ]
